name: notifku
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  workmanager: ^0.5.1
  fluttericon: ^2.0.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3
  flutter_local_notifications: ^12.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
